# Site settings
title: "Intelligent Investing, LLC."
email: "team@variantstudios.com"
description: "Tax efficient investing and financial life planning."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
#timezone: America/Denver - Don't set for CloudCannon...for reasons.
version: "3.2.1" # the version of jekyll
author.name: "Variant Studios"
author.email: "team@variantstudios.com"

# Gems for plugins
gems:
  - jekyll-paginate # Needed to add paginate on Jekyll ver 3+
  - jekyll-sitemap # Simple jekyll plugin that creates a sitemap.xml file and you can exclude files by adding 'sitemap:false' to the frontmatter of any file(s).

# Permalinks
permalink: pretty

# Pagination
paginate: 10
paginate_path: '/:num/'

#Collections
collections:

defaults:

# typekit - Because we all need nice type faces.
typekit:

# Google Analytics - What site isn't using it?!
google_analytics_tracking_id:

exclude: ["vendor","node_modules","package.json","Gemfile","gulpfile.js","*.scss"]
